
[package]
name = "sorth"
version = "0.1.17"
edition = "2021"
authors = [ "Chloë Strainge nullptr.0@gmail.com" ]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
libffi = "3.2.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [ "consoleapi", "wincon", "processenv" ] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
